name: Node.js CI with Local SonarQube

on:
  push:
    branches: [ "master","nejdbedoui-patch-3" ]
  pull_request:
    branches: [ "master","nejdbedoui-patch-3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          sonar-token: "sqa_956e06b65236dba1f6bab8481c740593383bc768"
          projectBaseDir: ./
          sonar-project-version: 1.0
          sonar-host-url: http://192.168.1.60:9000/
