name: Node.js CI with Local SonarQube

on:
  push:
    branches: [ "master", "nejdbedoui-patch-3" ]
  pull_request:
    branches: [ "master", "nejdbedoui-patch-3" ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
  
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn install
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
